baseURL = "http://priscillaencarnacion.com"
languageCode = "en-us"
title = "Priscilla Encarnacion"
theme = "hugo-initio"

[params]
    name = "Priscilla Encarnacion"
    description = "Law Student @ UNC Chapel Hill"
    email = "prism@live.unc.edu"
    year = 2017
    picture="priscilla.jpg"

    showSubheader = true
    showServices = true
[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5
